### PR TITLE
Update requirements.txt to add pysaml2 requirement

### PR DESCRIPTION
**Pull request by erichester76**
added pysaml2 so saml2 based configs wont require a custom docker build

### CODE REVIEW

**Comment by erichester76** [comment]
Might not be an issue since it appears the 7.x webui doesnt support SAML (yet?). Does at least help for 6.x builds

**Comment by satterly** [comment]
You're right, SAML2 isn't supported in web UI 7.x as I don't have any easy way to develop and test against SAML2.

If you can advise on how this could be done (easily) that would be appreciated. Using a SAML docker image, perhaps?

**Comment by erichester76** [comment]
I think auth0 will give you a free account to setup a test idP

https://auth0.com/pricing

Eric Hester
eric.hester@gmail.com
864-593-2665

**Comment by erichester76** [comment]
I just got back to working on this.. i switched to azure ad oauth. I have
everything setup and am getting a reply token callback it seems, but I keep
getting this error: "Error: Must support one of the following OpenID
claims: 'preferred_username', 'nickname' or 'email' Do I need to add an
optional claim of some sort? Sorry, but there is no documentation on azure
yet so I am using the generic oauth2 doc and found the azure_tenant
directive by looking in the code.

Eric Hester
eric.hester@gmail.com
864-593-2665

**Comment by satterly** [comment]
Under "Azure Active Directory" I clicked on "App registrations" menu then "New Registration" button and filled in the callback URL where it says "Web" and clicked "Register" button. Then I had to go back in to the "App Registration" for that App and under "Redirect URLs" click "1 Web, 0 public client" and got the following page ...

Screenshot 2019-06-02 at 20 53 33

I then clicked the "ID Token" checkbox. Let me know if/when you've done all that and if that changes anything. Thanks.

**Comment by erichester76** [comment]
still getting the same error unfortunately.. I think there is a difference
in how the claims are returned between a personal and enterprise user..
I've read email claim is only returned on personal whereas
preferred_username is returned on enterprise. But I see in the code you are
looking for both so I am not sure whats up.

also just as a note, I had to go build a secret for the app and set that in
alertad.conf as well as far as configuration steps

Eric Hester
eric.hester@gmail.com
864-593-2665

**Comment by erichester76** [comment]
I think you need a similar assignment where you get preferred_username from
id_token also. back to my previous statement of the different handling of
returned data
subject = userinfo['sub'] name = userinfo.get('name') or
id_token.get('name') nickname = userinfo.get('nickname') email =
userinfo.get('email') or id_token.get('email') email_verified =
userinfo.get('email_verified', id_token.get('email_verified', bool(email)))
picture = userinfo.get('picture') or id_token.get('picture') role_claim =
current_app.config['OIDC_ROLE_CLAIM'] group_claim =
current_app.config['OIDC_GROUP_CLAIM'] custom_claims = { role_claim:
userinfo.get(role_claim) or id_token.get(role_claim, []), group_claim:
userinfo.get(group_claim) or id_token.get(group_claim, []), } login =
userinfo.get('preferred_username', nickname or email)
Eric Hester
eric.hester@gmail.com
864-593-2665

**Comment by satterly** [comment]
@erichester76 Can you let me know if Azure auth is working for you with the latest version? Thanks.

**Comment by satterly** [comment]
SAML2 not supported in web version 7 yet, so closing this PR for now.

**Pull request closed without merging**
