### PR TITLE
Add BASE_PATH to the k8s contrib

### PR DESCRIPTION
**Pull request by doodle-tnw**
Updates the k8s contrib inline with the main image to allow BASE_URL to be fully qualified

### CODE REVIEW

**Comment by satterly** [comment]
Are you sure this works? The PR you are referring to that changed the main image (#95) was much more involved and not just a matter of adding a new `BASE_PATH` environment variable.

Please confirm you have tested this and it works as expected. Thanks.

**Comment by doodle-tnw** [comment]
We had it running in our environment fine. The change you made was made more complicated by nginx, the nginx in the k8s contrib is standard default.conf because it doesn't have to expose it behind a base_path - the assumption in a k8s world would that the containers sit behind an ingress proxy, and are just upstream services to that.

**Comment by satterly** [comment]
Ok, but `BASE_PATH` can be derived from `BASE_URL`. The bash is not pretty but it means you don't need an extra environment variable and there's no chance that the two variables could point to different paths.
https://github.com/alerta/docker-alerta/blob/a020531c585f3038c0b60d53eb4b0e39b8199457/docker-entrypoint.sh#L20-L21
Note also line 21 where the `uwsgi.ini` needs to be parsed to ensure the mount point is set correctly. ie. you can't rely on a `BASE_URL` just being a path anymore.

**Comment by doodle-tnw** [comment]
Ah sorry, didn't catch that when I had a look through - that makes sense!

I'll make the change and push it

**Comment by satterly** [comment]
👍 Thanks! Sorry it took so long to merge this.

**Pull request merged**
