### PR TITLE
Fixed permission problem with nginx's log dir

### PR DESCRIPTION
**Pull request by moeterich**

### CODE REVIEW

**Comment by satterly** [comment]
Are you seeing nginx errors somewhere? nginx logs should be going to [stdout](https://github.com/alerta/docker-alerta/blob/master/nginx.conf#L34) [stderr](https://github.com/alerta/docker-alerta/blob/master/nginx.conf#L6)

**Comment by moeterich** [comment]
At startup time:

2018-03-08 20:14:01,330 DEBG 'nginx' stdout output:
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

**Comment by satterly** [comment]
Another option is to [symlink](https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.12/Dockerfile#L12) the nginx logfile to stdout/stderr. Might be worth trying that.

**Comment by moeterich** [comment]
Also a good solution

**Comment by moeterich** [comment]
Issue seems to be resolved by symlinking to stdout.

**Comment by satterly** [comment]
👍 Thanks.

**Pull request merged**
