### PR TITLE
Deployment of alerta to custom base path

### PR DESCRIPTION
**Pull request by acottais**
In order to facilitate the deployment of alerta behind a reverse proxy and set a base path (eg. http://example.com/alerta) the URL_PATH environment variable is added. URL_PATH (default to /) reflects the base path of the web ui, the API path will be set to URL_PATH/api and the BASE_URL environment variable will be overwritten with this value.

Path prefix are also substituted inside the index.html file of the web-ui package. For this to work, the web ui have to be built with root ( `/` ) as the public path.

Another variable is also added ( `CUSTOM_PLUGINS` ) to allows the installation of Alerta plugins from private repositories.

### CODE REVIEW

**Comment by satterly** [comment]
Thanks for the pull request. However, I'm not sure this is the right approach. There is an outstanding issue with how to deploy alerta web at a subpath as part of the standard build for the web UI (see alerta/alerta-webui#150) and I think adding yet another environment variable just complicates things even further.

Also, I'm [removing the ability to install plugins at container boot time for several reasons](#132) and so adding the ability to do this for custom plugins goes against Docker "best practices". (See comments [here](https://github.com/elastic/elasticsearch-docker/pull/26#issuecomment-278818245) and [here](https://github.com/elastic/elasticsearch-docker/issues/164))

**Comment by acottais** [comment]
Concerning the installation of the plugins I totally understand, I also had some security concerns due to the fact that you could install arbitrary code.
As for the subpath issue the current state of the alerta-web image does not work fully if you just set the BASE_URL variable at runtime: the first call will hit the subpath/index.html but as the web application is built with root it will overwrite the address in the browser. And also the js and css files might not load since the path is set to root ('/'). Another environment variable is maybe not the best approach but the web application need to be tweaked in order to be fully compatible with the subpath deployment (at least have the base_path in the config.json file and the src path in the html file). We can keep the BASE_URL parameter and inject those modifications in the entrypoint.

**Comment by satterly** [comment]
I think your suggestion above could work. We can derive "base_path" (eg. `/alerta/` subpath) from "BASE_URL" which historically points to the API endpoint (eg. `https://monitoring.example.com/alerta/api` or `/alerta/api` which assumes localhost).

Then set "base_path" in the `config.json` file to fix application javascript, and do a find-and-replace in the `index.html` sourcing the css and js files (which you had done already).

Do you want to have another go at this? 😄

**Comment by satterly** [comment]
I've had a go at this myself. Would be good if you could test it, if you have time. Thanks.

**Comment by acottais** [comment]
I did some test on your work. it's working fine.
There is still some minors issue on the nginx configuration, but it's more a personnal preference : when using a subpath the current nginx configuration will only allow subpath ending with an explicit '/' (eg. /alerta/ and not /alerta).

That is why I differentiated the WEB_URL (ending with a / ) and the WEB_PATH (stripped from the endind /) variable in the nginx.conf.

**Comment by satterly** [comment]
I see. Can you paste an exact example of what the nginx config would look like in that scenario? Thanks.

**Comment by acottais** [comment]
Based on your current code you could have something like:

nginx.conf:
```nginx
                location !WEB_URL! {
                        alias /web/;
                        try_files $uri $uri/ !WEB_PATH!index.html;
                }
```
docker_entrypoint.sh:
``` shell
  sed -i 's@!WEB_URL!@'"${WEB_PATH%/}"'@' /app/nginx.conf
```

**Pull request closed without merging**
