### PR TITLE
Add support for LDAP auth

### PR DESCRIPTION
**Pull request by sepich**
This adds `python-ldap` to image, so LDAP auth would work.
Tested with on-premises Active Directory.

### CODE REVIEW

**Comment by satterly** [comment]
Thanks! 👍 💯

**Comment by skbly7** [comment]
Because of how we are enabling LDAP login currently, image users would not be able to setup basic auth docker instances after this.
https://github.com/alerta/alerta/blob/master/alerta/auth/__init__.py#L8

**Comment by satterly** [comment]
@skbly7 That's correct. I should have realised that. Thanks for raising the issue. I'll need to revert this PR.

**Comment by satterly** [comment]
Building updated container now.

I will modify the entry point script to check the `AUTH_PROVIDER` environment variable and if set to "basic_ldap" it can then do the pip install command.

**Pull request merged**
