### PR TITLE
Allow setting admin key as Env variable

### PR DESCRIPTION
**Pull request by pbabics**

### CODE REVIEW

**Comment by satterly** [comment]
Would it be better to use "docker secrets" for this? https://docs.docker.com/engine/swarm/secrets/#intermediate-example-use-secrets-with-a-nginx-service

**Comment by pbabics** [comment]
Yes, but there is a question which docker version you want to support. Most of production implementations of alerta use docker version <= 17.05.

**Comment by satterly** [comment]
Looks like secret support was added in version [1.13.0](https://github.com/moby/moby/releases/tag/v1.13.0) back in January 2017.

**Comment by satterly** [comment]
After reviewing the current state of docker secrets this is the best approach at present. 👍

**Pull request merged**
